# Generated by Django 6.0.6 on 2026-06-05 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('generation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('payment_pending', 'Payment Pending'), ('paid', 'Paid'), ('sent_to_vendor', 'Sent To Vendor'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('shipping_snapshot', models.JSONField(blank=True, default=dict)),
                ('vendor_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='generation.imagegenerationjob')),
                ('product_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.producttemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
