# Generated by Django 6.0.6 on 2026-06-05 03:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('style', models.CharField(choices=[('futuristic', 'Futuristic'), ('streetwear', 'Streetwear'), ('minimal', 'Minimal'), ('poster_art', 'Poster Art')], default='futuristic', max_length=32)),
                ('product_intent', models.CharField(default='tshirt', max_length=80)),
                ('aspect_ratio', models.CharField(default='1:1', max_length=16)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='references/%Y/%m/')),
                ('output_image_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('provider', models.CharField(default='mock', max_length=80)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
